// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/shipping": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Realiza la busqueda de pedidos del usuario por defecto o email, id de paquete o número de paquete",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shipping"
                ],
                "summary": "Busqueda de paquetes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Correo electrónico del usuario a buscar",
                        "name": "email",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Código de paquete a buscar",
                        "name": "shipping_number",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Id de paquete a buscar",
                        "name": "id_shipping",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Lista de paquetes encontrados",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Shipping"
                            }
                        }
                    },
                    "400": {
                        "description": "Error en los datos proporcionados",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorMessage"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shipping"
                ],
                "summary": "Actualización de datos de paquete",
                "parameters": [
                    {
                        "description": "actualiza los datos del paquete",
                        "name": "shipping",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateShipping"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "mensaje de éxito",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessMessage"
                        }
                    },
                    "400": {
                        "description": "Error en el proceso",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorMessage"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Realiza el guardado del paquete que se quiere crear en la BD y una transacción se abre",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shipping"
                ],
                "summary": "Creación de paquete",
                "parameters": [
                    {
                        "description": "crea paquete y transacción",
                        "name": "shipping",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateShipping"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "mensaje de éxito",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessMessage"
                        }
                    },
                    "400": {
                        "description": "Error en los datos proporcionados",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorMessage"
                        }
                    }
                }
            }
        },
        "/shipping/close": {
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Shipping"
                ],
                "summary": "Cerrar paquete y creación de transacción",
                "parameters": [
                    {
                        "description": "toma el id del paquete para cerrarlo y crear transacción de cierre",
                        "name": "shipping",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CloseShipping"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "mensaje de éxito",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessMessage"
                        }
                    },
                    "400": {
                        "description": "Error en el proceso",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorMessage"
                        }
                    }
                }
            }
        },
        "/transaction": {
            "get": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction"
                ],
                "summary": "Estado de cuenta de usuario",
                "responses": {
                    "200": {
                        "description": "ESTADO DE SALDO Y PAQUETES QUE TIENE",
                        "schema": {
                            "$ref": "#/definitions/models.BalanceTransaction"
                        }
                    },
                    "400": {
                        "description": "Error en los datos proporcionados",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorMessage"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "JWT": []
                    }
                ],
                "description": "Realiza el guardado de la transacción que se quiere crear en la BD",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transaction"
                ],
                "summary": "Creación de transacción",
                "parameters": [
                    {
                        "description": "crea transacción",
                        "name": "shipping",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateTransaction"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "mensaje de éxito",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessMessage"
                        }
                    },
                    "400": {
                        "description": "Error en los datos proporcionados",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorMessage"
                        }
                    }
                }
            }
        },
        "/user": {
            "post": {
                "description": "Realiza el guardado del usuario en la BD",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Registro de usuario",
                "parameters": [
                    {
                        "description": "crea usuario",
                        "name": "User",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RegisterUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "mensaje de éxito",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessMessage"
                        }
                    },
                    "400": {
                        "description": "Error en los datos proporcionados",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorMessage"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "Realiza el guardado del usuario en la BD",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Inicio de sesión de usuario",
                "parameters": [
                    {
                        "description": "Email y contraseña",
                        "name": "User",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "mensaje de éxito",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "400": {
                        "description": "Error en los datos proporcionados",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorMessage"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.BalanceTransaction": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "number"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "models.CloseShipping": {
            "type": "object",
            "required": [
                "id_shipping"
            ],
            "properties": {
                "id_shipping": {
                    "type": "integer"
                }
            }
        },
        "models.CreateShipping": {
            "type": "object",
            "required": [
                "amount",
                "expiration_date",
                "quantity",
                "shipping_number",
                "username",
                "weight"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "expiration_date": {
                    "type": "string"
                },
                "id_user": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "shipping_number": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "models.CreateTransaction": {
            "type": "object",
            "required": [
                "amount",
                "id_shipping",
                "id_transaction_type",
                "id_user"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "id_shipping": {
                    "type": "integer"
                },
                "id_transaction_type": {
                    "type": "integer"
                },
                "id_user": {
                    "type": "integer"
                }
            }
        },
        "models.ErrorMessage": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "models.LoginUser": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.RegisterUser": {
            "type": "object",
            "required": [
                "cc",
                "email",
                "firstname",
                "password",
                "passwordc",
                "phonenumber",
                "username"
            ],
            "properties": {
                "cc": {
                    "type": "string"
                },
                "direction": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstname": {
                    "type": "string"
                },
                "lastname": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                },
                "passwordc": {
                    "type": "string"
                },
                "phonenumber": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.Shipping": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "created_date": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "expiration_date": {
                    "type": "string"
                },
                "id_shipping": {
                    "type": "integer"
                },
                "id_user": {
                    "type": "integer"
                },
                "last_update": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "shipping_number": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "models.SuccessMessage": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "models.UpdateShipping": {
            "type": "object",
            "required": [
                "id_shipping"
            ],
            "properties": {
                "amount": {
                    "type": "number"
                },
                "expiration_date": {
                    "type": "string"
                },
                "id_shipping": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "shipping_number": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "cc": {
                    "type": "string"
                },
                "created_date": {
                    "type": "string"
                },
                "direction": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstname": {
                    "type": "string"
                },
                "id_role": {
                    "type": "integer"
                },
                "id_user": {
                    "type": "integer"
                },
                "lastname": {
                    "type": "string"
                },
                "phone_number": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "JWT": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Tag Service API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
